const { docClient, TABLE_NAME } = require('./src/config/db');
const { v4: uuidv4 } = require('uuid');

// Sample job applications data
const sampleJobs = [
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4", // Your user ID from the logs
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Google",
    position: "Cloud Engineer",
    status: "Interview",
    location: "Mountain View, CA",
    salary: "$180k-$220k / yr",
    notes: "Technical interview scheduled next week with the cloud infrastructure team",
    dateApplied: new Date('2024-03-20').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Stripe",
    position: "DevOps Engineer",
    status: "Offer",
    location: "San Francisco, CA / Remote",
    salary: "$200k-$250k / yr",
    notes: "Received offer! 15% bonus + equity package. Need to respond by Friday",
    dateApplied: new Date('2024-03-15').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Vercel",
    position: "Site Reliability Engineer",
    status: "Applied",
    location: "Fully Remote",
    salary: "$160k-$190k / yr",
    notes: "Applied through LinkedIn referral from current employee",
    dateApplied: new Date('2024-03-22').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Amazon",
    position: "Solutions Architect",
    status: "Rejected",
    location: "Seattle, WA",
    salary: "$150k-$185k / yr",
    notes: "Rejected after final round. Good experience overall",
    dateApplied: new Date('2024-03-10').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Netflix",
    position: "Cloud Security Engineer",
    status: "Interview",
    location: "Los Gatos, CA",
    salary: "$220k-$280k / yr",
    notes: "Phone screen went well, technical round next Tuesday",
    dateApplied: new Date('2024-03-18').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Meta",
    position: "Production Engineer",
    status: "Ghosted",
    location: "Menlo Park, CA",
    salary: "$190k-$240k / yr",
    notes: "No response after 3 follow-ups. Moving on.",
    dateApplied: new Date('2024-03-05').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Apple",
    position: "Infrastructure Engineer",
    status: "Applied",
    location: "Cupertino, CA",
    salary: "$170k-$210k / yr",
    notes: "Applied through company website. Waiting for HR screening call",
    dateApplied: new Date('2024-03-25').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Microsoft",
    position: "Cloud Solutions Architect",
    status: "Interview",
    location: "Redmond, WA / Remote",
    salary: "$160k-$200k / yr",
    notes: "First round with hiring manager went well. System design interview scheduled",
    dateApplied: new Date('2024-03-21').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Tesla",
    position: "DevOps Engineer",
    status: "Rejected",
    location: "Palo Alto, CA",
    salary: "$140k-$180k / yr",
    notes: "Rejected after technical assessment. Focus more on Kubernetes next time",
    dateApplied: new Date('2024-03-08').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Spotify",
    position: "Site Reliability Engineer",
    status: "Offer",
    location: "Fully Remote",
    salary: "$150k-$190k / yr",
    notes: "Great team culture! Accepting this offer. Start date: May 1st",
    dateApplied: new Date('2024-03-12').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Airbnb",
    position: "Cloud Infrastructure Engineer",
    status: "Applied",
    location: "San Francisco, CA",
    salary: "$180k-$220k / yr",
    notes: "Referred by former colleague. Application under review",
    dateApplied: new Date('2024-03-24').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Dropbox",
    position: "DevOps Engineer",
    status: "Interview",
    location: "San Francisco, CA",
    salary: "$155k-$195k / yr",
    notes: "Coding challenge completed. Waiting for interview scheduling",
    dateApplied: new Date('2024-03-19').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Slack",
    position: "Production Engineer",
    status: "Rejected",
    location: "San Francisco, CA",
    salary: "$160k-$200k / yr",
    notes: "Not enough experience with large-scale distributed systems",
    dateApplied: new Date('2024-03-06').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "GitHub",
    position: "Site Reliability Engineer",
    status: "Interview",
    location: "Fully Remote",
    salary: "$140k-$180k / yr",
    notes: "Remote-first company! Interview with infrastructure team next week",
    dateApplied: new Date('2024-03-23').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Twilio",
    position: "Cloud Engineer",
    status: "Applied",
    location: "San Francisco, CA / Remote",
    salary: "$150k-$185k / yr",
    notes: "Applied through employee referral. API company with good culture",
    dateApplied: new Date('2024-03-26').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Stripe",
    position: "Security Engineer",
    status: "Ghosted",
    location: "San Francisco, CA",
    salary: "$200k-$250k / yr",
    notes: "No response after initial screening. Maybe try again later",
    dateApplied: new Date('2024-03-01').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Notion",
    position: "Infrastructure Engineer",
    status: "Interview",
    location: "Fully Remote",
    salary: "$130k-$170k / yr",
    notes: "Great product! Interview with CTO scheduled",
    dateApplied: new Date('2024-03-17').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Discord",
    position: "DevOps Engineer",
    status: "Applied",
    location: "San Francisco, CA / Remote",
    salary: "$145k-$185k / yr",
    notes: "Gaming company with interesting scale challenges",
    dateApplied: new Date('2024-03-25').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Figma",
    position: "Site Reliability Engineer",
    status: "Offer",
    location: "Fully Remote",
    salary: "$160k-$200k / yr",
    notes: "Amazing design tools! Great remote culture. Strong offer received",
    dateApplied: new Date('2024-03-14').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Linear",
    position: "Infrastructure Engineer",
    status: "Rejected",
    location: "Fully Remote",
    salary: "$120k-$150k / yr",
    notes: "Too focused on their specific tech stack. Good learning experience",
    dateApplied: new Date('2024-03-03').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "Cloudflare",
    position: "Systems Engineer",
    status: "Interview",
    location: "San Francisco, CA / Austin, TX",
    salary: "$140k-$180k / yr",
    notes: "Global scale CDN company. Technical interview next week",
    dateApplied: new Date('2024-03-20').toISOString(),
  },
  {
    userId: "9929f98e-a031-70a3-0751-8f7856883bf4",
    applicationId: uuidv4(),
    _id: uuidv4(),
    company: "DigitalOcean",
    position: "DevOps Engineer",
    status: "Applied",
    location: "New York, NY / Remote",
    salary: "$130k-$160k / yr",
    notes: "Cloud provider with developer-friendly approach",
    dateApplied: new Date('2024-03-26').toISOString(),
  }
];

async function seedDatabase() {
  console.log('🌱 Starting to seed database with sample job applications...');
  
  try {
    for (const job of sampleJobs) {
      const params = {
        TableName: TABLE_NAME,
        Item: job,
      };
      
      await docClient.put(params).promise();
      console.log(`✅ Added: ${job.position} at ${job.company}`);
    }
    
    console.log(`\n🎉 Successfully seeded ${sampleJobs.length} job applications!`);
    console.log('📊 Your dashboard should now show these entries.\n');
    
  } catch (error) {
    console.error('❌ Error seeding database:', error);
  }
}

// Run the seed function
seedDatabase();
